-- Streaming-catalog schema for LML#842: the row-level PG canonical replacing
-- the whole-file streaming_availability.db lineage.
--
-- This file is the canonical DDL reference for the four `lml_cache` tables the
-- offline streaming enrichment pipeline writes: `streaming_album` (one row per
-- deduplicated library album, Discogs match group included),
-- `streaming_album_service` (one row per album x service probe outcome),
-- `streaming_track_result` (compilation-track resolution), and
-- `streaming_coverage_baseline` (write-side floor metrics for the export's
-- regression assertion). All live in the LML-owned `lml_cache.*` schema (per
-- WXYC/discogs-etl#288, Option 3) and are bootstrapped from LML's own FastAPI
-- lifespan and the offline DAO — no discogs-cache coordination; discogs-cache
-- tooling never touches `lml_cache.*`.
--
-- Distinct from `lml_cache.album_streaming_url_cache` (the runtime lookup
-- post-process cache keyed on normalized request strings): this is the offline
-- catalog keyed on library-album identity.
--
-- This file exists so:
--
--   1. The LML PR's reviewer has the DDL inline for comparison.
--   2. An operator can apply the schema directly to a non-discogs-cache PG
--      (e.g. local dev) without booting the full LML app.
--
-- The runtime source of truth is `entity/streaming_catalog.py`
-- (`set_up_streaming_catalog_schema`), which issues these statements on every
-- boot: `IF NOT EXISTS` for schema/tables/indexes, `CREATE OR REPLACE` for the
-- guard functions and triggers (triggers have no `IF NOT EXISTS`; OR REPLACE is
-- the idempotent form, PG14+ — this deliberately extends the `lml_cache.*`
-- bootstrap convention beyond CREATE-TABLE-only). The bootstrap runs all of it
-- as one transaction on one connection, after `SET LOCAL lock_timeout = '10s'`
-- and `SELECT pg_advisory_xact_lock(842001)` — bounded lock waits, serialized
-- concurrent boots, and never tables without their guard triggers. If the
-- canonical shape changes, update both places (a normalized-containment test
-- in tests/unit/test_streaming_catalog_schema.py pins every runtime statement,
-- PL/pgSQL bodies included, to this file).

CREATE SCHEMA IF NOT EXISTS lml_cache;

CREATE TABLE IF NOT EXISTS lml_cache.streaming_album (
    -- GENERATED BY DEFAULT (not ALWAYS): the one-time seed inserts the legacy
    -- SQLite ids verbatim so track_results.album_id references stay valid,
    -- then advances the sequence past max(id).
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_artist TEXT NOT NULL,
    normalized_title TEXT NOT NULL,
    display_artist TEXT NOT NULL,
    display_title TEXT NOT NULL,
    -- JSON arrays in SQLite TEXT today; JSONB here.
    library_ids JSONB NOT NULL DEFAULT '[]',
    formats JSONB NOT NULL DEFAULT '[]',
    genre TEXT,
    label TEXT,
    is_compilation BOOLEAN NOT NULL DEFAULT FALSE,
    is_single BOOLEAN NOT NULL DEFAULT FALSE,
    -- Discogs match group: metadata about which Discogs release this library
    -- album is — album identity, not a streaming probe result, hence kept
    -- here rather than as a service row.
    discogs_release_id BIGINT,
    discogs_artist TEXT,
    discogs_title TEXT,
    discogs_status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (normalized_artist, normalized_title)
);

CREATE TABLE IF NOT EXISTS lml_cache.streaming_album_service (
    -- ON DELETE RESTRICT: deleting an album must never silently take its
    -- collected probe rows with it.
    album_id BIGINT NOT NULL REFERENCES lml_cache.streaming_album(id) ON DELETE RESTRICT,
    -- Service discriminator. The named CHECK pins the allowed set; the legacy
    -- SQLite drift columns (tidal_url, youtube_music_url, soundcloud_url) map
    -- onto these values at seed time. A new service is added by extending
    -- `_SERVICES` in the runtime module; the idempotent ALTER below picks it
    -- up on existing tables.
    service TEXT NOT NULL,
    -- 'pending' | 'found' | 'not_found' | 'error' (plus service-specific
    -- values the pipelines already use; deliberately not CHECK-pinned).
    status TEXT NOT NULL DEFAULT 'pending',
    url TEXT,
    slug TEXT,             -- bandcamp only
    service_item_id TEXT,  -- spotify_id today; service-scoped opaque id
    -- DOUBLE PRECISION (not REAL): SQLite REAL is an 8-byte double; float4
    -- would silently narrow the seeded values.
    confidence DOUBLE PRECISION,
    matched_artist TEXT,
    matched_title TEXT,
    checked_at TIMESTAMPTZ,
    PRIMARY KEY (album_id, service),
    CONSTRAINT streaming_album_service_valid CHECK (
        service IN ('spotify', 'deezer', 'apple_music', 'bandcamp', 'tidal',
                    'youtube_music', 'soundcloud')
    )
);

-- Idempotent widen of the named CHECK so an already-created table (where
-- `CREATE TABLE IF NOT EXISTS` is a no-op) picks up service values added after
-- its creation. Byte-stable across boots; runs atomically within the one
-- statement. Generated from `_SERVICES` in the runtime module.
ALTER TABLE lml_cache.streaming_album_service
    DROP CONSTRAINT IF EXISTS streaming_album_service_valid,
    ADD CONSTRAINT streaming_album_service_valid CHECK (
        service IN ('spotify', 'deezer', 'apple_music', 'bandcamp', 'tidal',
                    'youtube_music', 'soundcloud')
    );

-- Pending-scan support for the pipelines ("next albums to probe on service
-- X"), mirroring the legacy per-service status indexes.
CREATE INDEX IF NOT EXISTS idx_streaming_album_service_status
    ON lml_cache.streaming_album_service (service, status);

CREATE TABLE IF NOT EXISTS lml_cache.streaming_track_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL REFERENCES lml_cache.streaming_album(id) ON DELETE RESTRICT,
    artist TEXT NOT NULL,
    title TEXT NOT NULL,
    position TEXT,
    -- NOT NULL: every legacy SQLite row carries both provenance columns; the
    -- seed must not be able to silently drop them.
    source TEXT NOT NULL,
    source_type TEXT NOT NULL,
    -- Per-track resolution state ('pending' | 'local_match' | 'api_match' |
    -- 'not_found' | ...); the table stays wide (vs service rows) because this
    -- status is per-track and only spotify/deezer apply to tracks.
    resolution_status TEXT NOT NULL DEFAULT 'pending',
    resolved_via TEXT,
    resolved_album_id BIGINT,
    resolved_release_id BIGINT,
    spotify_url TEXT,
    spotify_confidence DOUBLE PRECISION,
    deezer_url TEXT,
    deezer_confidence DOUBLE PRECISION,
    checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Doubles as the FK-side index for the ON DELETE RESTRICT check (leading
    -- album_id), so no separate album index is needed.
    UNIQUE (album_id, artist, title)
);

CREATE INDEX IF NOT EXISTS idx_streaming_track_result_status
    ON lml_cache.streaming_track_result (resolution_status);

-- Write-side floor metrics (one row per metric, e.g. 'apple_music_found').
-- Refreshed only at the end of successful pipeline runs — never by the daily
-- read-only export — so the export's floor assertion can't track a slow bleed
-- downward. Restores #672's batch-regression detection (many small permitted
-- removals adding up) that the per-row triggers can't see.
CREATE TABLE IF NOT EXISTS lml_cache.streaming_coverage_baseline (
    metric TEXT PRIMARY KEY,
    value BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- No-regress guards: transitions that would discard collected streaming data
-- (nulling or blanking-to-'' a found URL, demoting a found album-service
-- status or a resolved track resolution_status, any DELETE, any TRUNCATE) are
-- rejected at the database unless the transaction opts in:
--
--   BEGIN;
--   SELECT set_config('lml_cache.allow_url_removal', 'on', true);
--   -- SELECT the scope first, then the targeted UPDATE/DELETE
--   COMMIT;
--
-- The third set_config argument (is_local) confines the opt-in to the
-- transaction; protection is restored automatically at COMMIT/ROLLBACK.
-- Runbook: docs/scripts.md.

CREATE OR REPLACE FUNCTION lml_cache.guard_streaming_album_service()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('lml_cache.allow_url_removal', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'streaming_album_service: DELETE blocked (album_id=%, service=%) — '
            'would discard collected streaming data; opt in via '
            'set_config(''lml_cache.allow_url_removal'', ''on'', true) in this transaction',
            OLD.album_id, OLD.service;
    END IF;
    IF (OLD.url IS NOT NULL AND OLD.url <> '')
        AND (NEW.url IS NULL OR NEW.url = '') THEN
        RAISE EXCEPTION 'streaming_album_service: discarding a found url blocked '
            '(album_id=%, service=%); opt in via '
            'set_config(''lml_cache.allow_url_removal'', ''on'', true) in this transaction',
            OLD.album_id, OLD.service;
    END IF;
    IF OLD.status = 'found' AND NEW.status IN ('not_found', 'error') THEN
        RAISE EXCEPTION 'streaming_album_service: demoting found status to % blocked '
            '(album_id=%, service=%); opt in via '
            'set_config(''lml_cache.allow_url_removal'', ''on'', true) in this transaction',
            NEW.status, OLD.album_id, OLD.service;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER streaming_album_service_no_regress
BEFORE UPDATE OR DELETE ON lml_cache.streaming_album_service
FOR EACH ROW EXECUTE FUNCTION lml_cache.guard_streaming_album_service();

CREATE OR REPLACE FUNCTION lml_cache.guard_streaming_track_result()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('lml_cache.allow_url_removal', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'streaming_track_result: DELETE blocked (id=%) — would discard '
            'collected streaming data; opt in via '
            'set_config(''lml_cache.allow_url_removal'', ''on'', true) in this transaction',
            OLD.id;
    END IF;
    IF ((OLD.spotify_url IS NOT NULL AND OLD.spotify_url <> '')
            AND (NEW.spotify_url IS NULL OR NEW.spotify_url = ''))
        OR ((OLD.deezer_url IS NOT NULL AND OLD.deezer_url <> '')
            AND (NEW.deezer_url IS NULL OR NEW.deezer_url = '')) THEN
        RAISE EXCEPTION 'streaming_track_result: discarding a found track url blocked (id=%); '
            'opt in via set_config(''lml_cache.allow_url_removal'', ''on'', true) '
            'in this transaction',
            OLD.id;
    END IF;
    IF OLD.resolution_status IN ('local_match', 'api_match')
        AND NEW.resolution_status IN ('not_found', 'error', 'false_positive') THEN
        RAISE EXCEPTION 'streaming_track_result: demoting resolution_status % to % blocked '
            '(id=%); opt in via '
            'set_config(''lml_cache.allow_url_removal'', ''on'', true) in this transaction',
            OLD.resolution_status, NEW.resolution_status, OLD.id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER streaming_track_result_no_regress
BEFORE UPDATE OR DELETE ON lml_cache.streaming_track_result
FOR EACH ROW EXECUTE FUNCTION lml_cache.guard_streaming_track_result();

-- TRUNCATE never fires row-level triggers, so without these the row guards
-- leave a one-statement wipe path open. One shared statement-level guard
-- closes it for both result tables; streaming_album itself is covered
-- transitively (bare TRUNCATE errors on the inbound FKs, and CASCADE reaches
-- these guards). Same GUC opts in.

CREATE OR REPLACE FUNCTION lml_cache.guard_streaming_truncate()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('lml_cache.allow_url_removal', true) = 'on' THEN
        RETURN NULL;
    END IF;
    RAISE EXCEPTION '%: TRUNCATE blocked — would discard all collected streaming data; '
        'opt in via set_config(''lml_cache.allow_url_removal'', ''on'', true) in this transaction',
        TG_TABLE_NAME;
END;
$$;

CREATE OR REPLACE TRIGGER streaming_album_service_no_truncate
BEFORE TRUNCATE ON lml_cache.streaming_album_service
FOR EACH STATEMENT EXECUTE FUNCTION lml_cache.guard_streaming_truncate();

CREATE OR REPLACE TRIGGER streaming_track_result_no_truncate
BEFORE TRUNCATE ON lml_cache.streaming_track_result
FOR EACH STATEMENT EXECUTE FUNCTION lml_cache.guard_streaming_truncate();
