-- Streaming-URL cache schema for LML#573.
--
-- Canonical DDL reference for the polymorphic
-- `lml_cache.album_streaming_url_cache` table, keyed on
-- `(service, artist_normalized, album_normalized)`. Generalizes the
-- Apple-Music-specific `entity.album_apple_music_lookup_cache` (LML#571)
-- into one table keyed on `service` (LML#573).
--
-- It lives in the LML-owned `lml_cache.*` schema (per WXYC/discogs-etl#288,
-- Option 3) -- not the discogs-cache-owned `entity.*` identity contract,
-- which is created and migrated only via discogs-cache alembic migrations --
-- and is bootstrapped from LML's own FastAPI lifespan; discogs-cache tooling
-- never touches `lml_cache.*`.
--
-- This file exists so:
--
--   1. The LML PR's reviewer has the DDL inline for comparison.
--   2. An operator can apply the schema directly to a non-discogs-cache PG
--      (e.g. local dev) without booting the full LML app.
--
-- GENERATED FILE -- regenerate via:
--   uv run python -m scripts.regenerate_lml_cache_sql
-- Statements come verbatim from `entity/streaming_url_cache.py`; do not hand-edit
-- this file -- a per-module unit test (`tests/unit/test_streaming_url_cache_schema.py`)
-- pins the statement text. The runtime source of truth is
-- `entity/streaming_url_cache.py`'s `set_up_streaming_url_cache_schema`, which issues these statements
-- (`IF NOT EXISTS` forms) on every boot.
--
-- The trailing widen-only DO block (LML#1038: generated by
-- `entity.ddl.build_widen_service_check_sql`, shared with
-- `entity/streaming_catalog.py` and `entity/track_streaming_url_cache.py`)
-- lets an already-created table (where `CREATE TABLE IF NOT EXISTS` is a
-- no-op) pick up service values added to `_SERVICES` after its creation --
-- see `entity/ddl.py` for the full merge-never-narrow / round-trip /
-- foreign-form-warn-and-skip rationale.

CREATE SCHEMA IF NOT EXISTS lml_cache;

-- `service` -- discriminator; the named CHECK constraint pins the allowed
-- set so a typo'd service key fails loudly at write time rather than
-- minting a silently-unreadable row (PR-3 added 'bandcamp'; a new service
-- extends `_SERVICES`, which both the CREATE-time CHECK and the widen block
-- below read from). `url` -- NULL records a known miss, gated by
-- `last_checked_at`'s TTL (LML#576: staleness is a SQL-side filter); a
-- non-null `url` is a durable hit that never goes stale. `is_error`
-- (LML#1121) marks a null-`url` row as a transport failure ("couldn't ask")
-- rather than a genuine confirmed absence, so it ages on the much shorter
-- `error_ttl` instead of `miss_ttl` -- see the footer below for tables that
-- predate the column.

CREATE TABLE IF NOT EXISTS lml_cache.album_streaming_url_cache (
    service TEXT NOT NULL,
    artist_normalized TEXT NOT NULL,
    album_normalized TEXT NOT NULL,
    url TEXT,
    is_error BOOLEAN NOT NULL DEFAULT false,
    last_checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (service, artist_normalized, album_normalized),
    CONSTRAINT album_streaming_url_cache_service_valid CHECK (
        service IN ('apple_music_album', 'spotify_album', 'bandcamp', 'youtube_music_album')
    )
);

DO $widen_service_check$
DECLARE
    existing_def text;
    inner_array text;
    existing_services text[];
    rebuilt_array text;
    code_services text[] := ARRAY[
        'apple_music_album', 'spotify_album', 'bandcamp', 'youtube_music_album'];
    merged_list text;
BEGIN
    SELECT pg_get_constraintdef(oid) INTO existing_def
        FROM pg_constraint
        WHERE conrelid = 'lml_cache.album_streaming_url_cache'::regclass
            AND conname = 'album_streaming_url_cache_service_valid';
    IF existing_def IS NOT NULL THEN
        inner_array := substring(
            existing_def FROM '^CHECK \(\(service = ANY \(ARRAY\[(.*)\]\)\)\)$'
        );
        IF inner_array IS NULL THEN
            RAISE WARNING 'album_streaming_url_cache_service_valid: deployed CHECK (%) is not in the '
                'expected service = ANY (ARRAY[...]) shape this bootstrap can parse; '
                'leaving it untouched (foreign-form policy: warn-and-skip)', existing_def;
            RETURN;
        END IF;
        SELECT array_agg(replace(m[1], '''''', '''')) INTO existing_services
            FROM regexp_matches(inner_array, '''((?:[^'']|'''')*)''', 'g') AS m;
        SELECT string_agg(quote_literal(s) || '::text', ', ') INTO rebuilt_array
            FROM unnest(existing_services) AS s;
        IF rebuilt_array IS DISTINCT FROM inner_array THEN
            RAISE WARNING 'album_streaming_url_cache_service_valid: deployed CHECK (%) has literals this '
                'bootstrap could not confidently round-trip; leaving it untouched '
                '(foreign-form policy: warn-and-skip)', existing_def;
            RETURN;
        END IF;
        IF existing_services @> code_services THEN
            RETURN;
        END IF;
    ELSE
        SELECT array_agg(DISTINCT service) INTO existing_services
            FROM lml_cache.album_streaming_url_cache;
    END IF;
    SELECT string_agg(DISTINCT quote_literal(s), ', ' ORDER BY quote_literal(s))
        INTO merged_list
        FROM unnest(coalesce(existing_services, ARRAY[]::text[]) || code_services) AS s;
    EXECUTE 'ALTER TABLE lml_cache.album_streaming_url_cache '
        'DROP CONSTRAINT IF EXISTS album_streaming_url_cache_service_valid, '
        'ADD CONSTRAINT album_streaming_url_cache_service_valid CHECK (service IN ('
        || merged_list || '))';
END;
$widen_service_check$;

-- LML#1121: `is_error` marks a null-`url` row as a transport failure
-- ("couldn't ask") apart from a genuine confirmed absence, so it ages on a
-- much shorter `error_ttl` instead of the 7-day `miss_ttl`. A fresh install
-- already has the column from the CREATE TABLE above; the runtime bootstrap
-- additionally issues this idempotent ALTER (not shown as a top-level
-- statement -- it is a follow-up upgrade for a table that predates the
-- column, a no-op once the column exists) so an existing prod table gains it
-- in place. Mirrors `entity/release_resolution_cache.py`'s `crowd_out`
-- upgrade (LML#824):
--
--   ALTER TABLE lml_cache.album_streaming_url_cache ADD COLUMN IF NOT EXISTS is_error BOOLEAN NOT NULL DEFAULT false;
