"""Row-level PG canonical for the offline streaming-availability catalog (LML#842).

The offline enrichment pipeline (``scripts/streaming_availability/``,
``scripts/track_streaming/``, ``scripts/bandcamp_pipeline.py``) historically
wrote a whole SQLite file (``streaming_availability.db``) that was clobber-
uploaded to object storage — the two-lineages anti-pattern #672 paid down for
the volume/bucket fork. This module owns the DDL for its replacement: four
tables in the LML-owned ``lml_cache.*`` schema (discogs-etl#288 Option 3) on
the shared discogs-cache PostgreSQL.

* ``lml_cache.streaming_album`` — one row per deduplicated library album
  (identity, Discogs match group). Seeded from the SQLite ``albums`` table
  with ids preserved, hence ``GENERATED BY DEFAULT AS IDENTITY``.
* ``lml_cache.streaming_album_service`` — one row per (album, service) probe
  outcome. Normalized service rows (vs the wide SQLite columns) dissolve the
  drift-column problem: ``tidal``/``youtube_music``/``soundcloud`` are
  ordinary service values, and adding a service is a CHECK-widen via the same
  ``_DDL_ALTER_CHECK`` pattern as ``entity/streaming_url_cache.py``.
* ``lml_cache.streaming_track_result`` — compilation-track resolution; stays
  wide because ``resolution_status`` is per-track and only spotify/deezer
  apply.
* ``lml_cache.streaming_coverage_baseline`` — one row per coverage metric,
  refreshed only from the write path (pipeline runs), read by the export's
  floor assertion. Restores #672's batch-regression detection (many small
  permitted removals adding up) that the per-row triggers can't see.

Distinct from the runtime ``lml_cache.album_streaming_url_cache`` (lookup
post-process cache keyed on normalized request strings): this is the offline
catalog keyed on library-album identity. Do not conflate them.

**No-regress guards.** ``BEFORE UPDATE OR DELETE`` triggers on the two result
tables structurally replace the #672 whole-file coverage guard: a transition
that would discard collected streaming data — nulling a found URL, demoting a
``found`` status to ``not_found``/``error``, or any ``DELETE`` — is rejected
at the database, not detected after the fact. Streaming URLs are rate-limited
API results and expensive to replace (org data-safety rules). Legitimate
revocation (bad-URL stripping, dedup repair) opts in per transaction::

    BEGIN;
    SELECT set_config('lml_cache.allow_url_removal', 'on', true);
    -- SELECT the scope first, then the targeted UPDATE/DELETE
    COMMIT;

The runbook lives in ``docs/scripts.md``. No DAO revocation method exists on
purpose — the only URL-stripping scripts are in the archived do-not-port set.

**Bootstrap convention note.** Triggers and PL/pgSQL functions have no ``IF
NOT EXISTS``, so this module extends the ``lml_cache.*`` boot convention with
``CREATE OR REPLACE FUNCTION`` / ``CREATE OR REPLACE TRIGGER`` (PG14+; the
discogs-cache runs PG17) — idempotent by replacement, byte-stable across
boots. ``set_up_streaming_catalog_schema`` is called from the ``main.py``
lifespan (fifth ``set_up_*`` call) and, in later PRs, from the offline DAO's
``connect()`` so scripts don't depend on a deployed app having booted first.
"""

from __future__ import annotations

from entity.sources import PgSource

# The services a catalog probe can target. The named CHECK pins this set at
# the DB level; the seed maps the SQLite wide columns (spotify_*, deezer_*,
# apple_*, bandcamp_*) and the real prod file's drift columns (tidal_url,
# youtube_music_url, soundcloud_url) onto these values. Adding a service
# extends this tuple and the ALTER below picks it up.
_SERVICES = (
    "spotify",
    "deezer",
    "apple_music",
    "bandcamp",
    "tidal",
    "youtube_music",
    "soundcloud",
)

# Shared IN-list literal so the CREATE-time CHECK and the idempotent ALTER are
# generated from the same source — they can never drift.
_SERVICE_IN_LIST = ", ".join(f"'{s}'" for s in _SERVICES)

# Transaction-local GUC consulted by both guard functions. Set via
# ``set_config('lml_cache.allow_url_removal', 'on', true)`` — the ``true``
# (is_local) confines the opt-in to the enclosing transaction, so protection
# is restored automatically at COMMIT/ROLLBACK.
ALLOW_URL_REMOVAL_GUC = "lml_cache.allow_url_removal"

_DDL_SCHEMA = "CREATE SCHEMA IF NOT EXISTS lml_cache"

# ``GENERATED BY DEFAULT`` (not ``ALWAYS``): the one-time seed inserts SQLite
# ids verbatim to keep ``track_results.album_id`` references valid, then
# advances the sequence past max(id).
_DDL_ALBUM = """\
CREATE TABLE IF NOT EXISTS lml_cache.streaming_album (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_artist TEXT NOT NULL,
    normalized_title TEXT NOT NULL,
    display_artist TEXT NOT NULL,
    display_title TEXT NOT NULL,
    library_ids JSONB NOT NULL DEFAULT '[]',
    formats JSONB NOT NULL DEFAULT '[]',
    genre TEXT,
    label TEXT,
    is_compilation BOOLEAN NOT NULL DEFAULT FALSE,
    is_single BOOLEAN NOT NULL DEFAULT FALSE,
    discogs_release_id BIGINT,
    discogs_artist TEXT,
    discogs_title TEXT,
    discogs_status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (normalized_artist, normalized_title)
)\
"""

# Named CHECK constraint (``streaming_album_service_valid``) avoids reliance
# on PG auto-naming so the ALTER below can DROP/ADD it by name. ``ON DELETE
# RESTRICT`` (not CASCADE): deleting an album must never silently take its
# collected probe rows with it.
_DDL_ALBUM_SERVICE = f"""\
CREATE TABLE IF NOT EXISTS lml_cache.streaming_album_service (
    album_id BIGINT NOT NULL REFERENCES lml_cache.streaming_album(id) ON DELETE RESTRICT,
    service TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    url TEXT,
    slug TEXT,
    service_item_id TEXT,
    confidence REAL,
    matched_artist TEXT,
    matched_title TEXT,
    checked_at TIMESTAMPTZ,
    PRIMARY KEY (album_id, service),
    CONSTRAINT streaming_album_service_valid CHECK (
        service IN ({_SERVICE_IN_LIST})
    )
)\
"""

# Idempotent widen of the named CHECK — same rationale and cost note as
# ``entity/streaming_url_cache.py``: CREATE TABLE IF NOT EXISTS is a no-op on
# an existing table, so a new ``_SERVICES`` value only reaches deployed tables
# through this DROP-IF-EXISTS + ADD pair (atomic within the one statement; the
# re-validation seq scan on boot is acceptable at this table's size).
_DDL_ALBUM_SERVICE_ALTER_CHECK = f"""\
ALTER TABLE lml_cache.streaming_album_service
    DROP CONSTRAINT IF EXISTS streaming_album_service_valid,
    ADD CONSTRAINT streaming_album_service_valid CHECK (
        service IN ({_SERVICE_IN_LIST})
    )\
"""

# Pending-scan support for the pipelines ("next albums to probe on service X"),
# mirroring the SQLite per-service status indexes.
_DDL_ALBUM_SERVICE_STATUS_INDEX = (
    "CREATE INDEX IF NOT EXISTS idx_streaming_album_service_status "
    "ON lml_cache.streaming_album_service (service, status)"
)

# ``UNIQUE (album_id, artist, title)`` doubles as the FK-side index for the
# ON DELETE RESTRICT check (leading album_id), so no separate album index.
_DDL_TRACK_RESULT = """\
CREATE TABLE IF NOT EXISTS lml_cache.streaming_track_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL REFERENCES lml_cache.streaming_album(id) ON DELETE RESTRICT,
    artist TEXT NOT NULL,
    title TEXT NOT NULL,
    position TEXT,
    source TEXT,
    source_type TEXT,
    resolution_status TEXT NOT NULL DEFAULT 'pending',
    resolved_via TEXT,
    resolved_album_id BIGINT,
    resolved_release_id BIGINT,
    spotify_url TEXT,
    spotify_confidence REAL,
    deezer_url TEXT,
    deezer_confidence REAL,
    checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (album_id, artist, title)
)\
"""

_DDL_TRACK_RESULT_STATUS_INDEX = (
    "CREATE INDEX IF NOT EXISTS idx_streaming_track_result_status "
    "ON lml_cache.streaming_track_result (resolution_status)"
)

# Write-side floor metrics (one row per metric, e.g. 'apple_music_found').
# Refreshed only at the end of successful pipeline runs — never by the daily
# read-only export — so the export's floor assertion can't track a slow bleed
# downward.
_DDL_COVERAGE_BASELINE = """\
CREATE TABLE IF NOT EXISTS lml_cache.streaming_coverage_baseline (
    metric TEXT PRIMARY KEY,
    value BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)\
"""

_DDL_GUARD_ALBUM_SERVICE_FN = f"""\
CREATE OR REPLACE FUNCTION lml_cache.guard_streaming_album_service()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('{ALLOW_URL_REMOVAL_GUC}', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'streaming_album_service: DELETE blocked (album_id=%, service=%) — '
            'would discard collected streaming data; opt in via '
            'set_config(''{ALLOW_URL_REMOVAL_GUC}'', ''on'', true) in this transaction',
            OLD.album_id, OLD.service;
    END IF;
    IF OLD.url IS NOT NULL AND NEW.url IS NULL THEN
        RAISE EXCEPTION 'streaming_album_service: nulling a found url blocked '
            '(album_id=%, service=%); opt in via '
            'set_config(''{ALLOW_URL_REMOVAL_GUC}'', ''on'', true) in this transaction',
            OLD.album_id, OLD.service;
    END IF;
    IF OLD.status = 'found' AND NEW.status IN ('not_found', 'error') THEN
        RAISE EXCEPTION 'streaming_album_service: demoting found status to % blocked '
            '(album_id=%, service=%); opt in via '
            'set_config(''{ALLOW_URL_REMOVAL_GUC}'', ''on'', true) in this transaction',
            NEW.status, OLD.album_id, OLD.service;
    END IF;
    RETURN NEW;
END;
$$\
"""

_DDL_GUARD_ALBUM_SERVICE_TRIGGER = """\
CREATE OR REPLACE TRIGGER streaming_album_service_no_regress
BEFORE UPDATE OR DELETE ON lml_cache.streaming_album_service
FOR EACH ROW EXECUTE FUNCTION lml_cache.guard_streaming_album_service()\
"""

_DDL_GUARD_TRACK_RESULT_FN = f"""\
CREATE OR REPLACE FUNCTION lml_cache.guard_streaming_track_result()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('{ALLOW_URL_REMOVAL_GUC}', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'streaming_track_result: DELETE blocked (id=%) — would discard '
            'collected streaming data; opt in via '
            'set_config(''{ALLOW_URL_REMOVAL_GUC}'', ''on'', true) in this transaction',
            OLD.id;
    END IF;
    IF (OLD.spotify_url IS NOT NULL AND NEW.spotify_url IS NULL)
        OR (OLD.deezer_url IS NOT NULL AND NEW.deezer_url IS NULL) THEN
        RAISE EXCEPTION 'streaming_track_result: nulling a found track url blocked (id=%); '
            'opt in via set_config(''{ALLOW_URL_REMOVAL_GUC}'', ''on'', true) '
            'in this transaction',
            OLD.id;
    END IF;
    RETURN NEW;
END;
$$\
"""

_DDL_GUARD_TRACK_RESULT_TRIGGER = """\
CREATE OR REPLACE TRIGGER streaming_track_result_no_regress
BEFORE UPDATE OR DELETE ON lml_cache.streaming_track_result
FOR EACH ROW EXECUTE FUNCTION lml_cache.guard_streaming_track_result()\
"""

# Ordered: schema first, parents before children (FKs), tables before their
# ALTER/indexes/triggers. Kept as a module constant so the bootstrap and the
# unit parity tests reference one list.
_DDL_STATEMENTS = (
    _DDL_SCHEMA,
    _DDL_ALBUM,
    _DDL_ALBUM_SERVICE,
    _DDL_ALBUM_SERVICE_ALTER_CHECK,
    _DDL_ALBUM_SERVICE_STATUS_INDEX,
    _DDL_TRACK_RESULT,
    _DDL_TRACK_RESULT_STATUS_INDEX,
    _DDL_COVERAGE_BASELINE,
    _DDL_GUARD_ALBUM_SERVICE_FN,
    _DDL_GUARD_ALBUM_SERVICE_TRIGGER,
    _DDL_GUARD_TRACK_RESULT_FN,
    _DDL_GUARD_TRACK_RESULT_TRIGGER,
)


async def set_up_streaming_catalog_schema(pg: PgSource) -> None:
    """Apply the idempotent streaming-catalog DDL (tables, indexes, guards).

    Called from the ``main.py`` lifespan (same best-effort posture as the
    sibling ``set_up_*_schema`` helpers: if the discogs-cache PG is
    unreachable, the caller logs and continues) and, from PR B on, from the
    offline DAO's ``connect()``. Duck-typed on ``pg.execute`` so both call
    sites share this one bootstrap.

    Every statement is CREATE/ALTER — pure DDL, byte-stable across boots. The
    ``CREATE OR REPLACE`` function/trigger forms are the idempotent
    equivalents of ``IF NOT EXISTS`` (which triggers don't support); replacing
    an identical definition is a no-op in effect. The final ALTER widens the
    named service CHECK to the current ``_SERVICES`` set, which CREATE TABLE
    IF NOT EXISTS cannot do on an existing table.
    """
    for statement in _DDL_STATEMENTS:
        await pg.execute(statement)
