"""Unit tests for the shared Discogs rate-bucket schema bootstrap (LML#841).

Two surfaces, mirroring ``test_library_release_override_schema.py``. Added in
LML#1038 -- ``entity/discogs_rate_bucket.sql`` predates this file (the sidecar
existed with no dedicated parity test guarding it), so this closes that gap
now that the sidecar is generated by ``scripts/regenerate_lml_cache_sql.py``
alongside its six siblings:

* ``entity/discogs_rate_bucket.sql`` — the canonical-DDL reference file. It
  must describe the single-row ``lml_cache.discogs_rate_bucket`` table, so a
  reviewer / operator has the DDL inline.
* ``set_up_discogs_rate_bucket_schema`` — the lifespan bootstrap helper. It
  must issue ``CREATE SCHEMA`` then ``CREATE TABLE`` then the idempotent
  ``ON CONFLICT DO NOTHING`` seed, and nothing else.

PG is mocked; ``tests/integration/test_discogs_rate_bucket.py`` drives the
real DDL (and the atomic-acquire semantics) against PostgreSQL.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import AsyncMock

import pytest

from entity.discogs_rate_bucket import _DDL_TABLE, set_up_discogs_rate_bucket_schema
from entity.sources import PgSource
from tests.unit.conftest import extract_create_table as _extract_create_table
from tests.unit.conftest import strip_sql_comments as _strip_sql_comments

_SQL_REFERENCE = (
    Path(__file__).resolve().parent.parent.parent / "entity" / "discogs_rate_bucket.sql"
)


class TestCanonicalDDLReference:
    """``entity/discogs_rate_bucket.sql`` is the inline DDL reference."""

    def test_reference_file_exists(self):
        assert _SQL_REFERENCE.is_file()

    def test_targets_lml_cache_schema_and_table(self):
        ddl = _SQL_REFERENCE.read_text()
        assert "CREATE SCHEMA IF NOT EXISTS lml_cache" in ddl
        assert "lml_cache.discogs_rate_bucket" in ddl

    def test_bucket_key_is_primary_key(self):
        ddl = _SQL_REFERENCE.read_text()
        assert "bucket_key TEXT PRIMARY KEY" in ddl

    def test_has_the_expected_columns(self):
        ddl = _SQL_REFERENCE.read_text()
        for column in ("tokens", "capacity", "refill_per_sec", "last_refill"):
            assert column in ddl

    def test_module_create_table_matches_sql_reference(self):
        # Structural parity: the generated sidecar's CREATE TABLE (modulo
        # comments + trailing semicolon) must match the runtime _DDL_TABLE
        # constant byte-for-byte after normalization -- the same contract the
        # sibling schema tests enforce, so a change to one that forgets the
        # other (or a stale, un-regenerated sidecar) fails loudly here.
        ddl = _SQL_REFERENCE.read_text()
        sql_create = _extract_create_table(ddl)
        module_create = _strip_sql_comments(_DDL_TABLE).strip().rstrip(";")
        assert sql_create == module_create, (
            "entity/discogs_rate_bucket.sql CREATE TABLE drifted from the "
            "_DDL_TABLE in entity/discogs_rate_bucket.py — regenerate via "
            "scripts/regenerate_lml_cache_sql.py."
        )


@pytest.mark.asyncio
class TestSetUpDiscogsRateBucketSchema:
    """``set_up_discogs_rate_bucket_schema`` runs exactly the idempotent DDL + seed."""

    async def test_creates_schema_table_then_seeds(self):
        pg = AsyncMock(spec=PgSource)
        pg.execute = AsyncMock(return_value="CREATE")

        await set_up_discogs_rate_bucket_schema(
            pg, bucket_key="discogs", capacity=50, refill_per_sec=50 / 60
        )

        assert pg.execute.await_count == 3
        schema_sql = pg.execute.await_args_list[0].args[0]
        table_sql = pg.execute.await_args_list[1].args[0]
        seed_sql = pg.execute.await_args_list[2].args[0]
        assert "CREATE SCHEMA IF NOT EXISTS lml_cache" in schema_sql
        assert "CREATE TABLE IF NOT EXISTS lml_cache.discogs_rate_bucket" in table_sql
        assert "bucket_key TEXT PRIMARY KEY" in table_sql
        assert "INSERT INTO lml_cache.discogs_rate_bucket" in seed_sql
        assert "ON CONFLICT (bucket_key) DO NOTHING" in seed_sql

    async def test_seed_binds_the_given_bucket_key_and_capacity(self):
        pg = AsyncMock(spec=PgSource)
        pg.execute = AsyncMock(return_value="CREATE")

        await set_up_discogs_rate_bucket_schema(
            pg, bucket_key="discogs", capacity=50, refill_per_sec=50 / 60
        )

        seed_args = pg.execute.await_args_list[2].args
        assert seed_args[1:] == ("discogs", 50, 50 / 60)

    async def test_bootstrap_is_idempotent(self):
        pg = AsyncMock(spec=PgSource)
        pg.execute = AsyncMock(return_value="CREATE")

        await set_up_discogs_rate_bucket_schema(
            pg, bucket_key="discogs", capacity=50, refill_per_sec=50 / 60
        )
        first = [call.args for call in pg.execute.await_args_list]
        pg.execute.reset_mock()
        await set_up_discogs_rate_bucket_schema(
            pg, bucket_key="discogs", capacity=50, refill_per_sec=50 / 60
        )
        second = [call.args for call in pg.execute.await_args_list]

        assert first == second

    async def test_does_not_touch_other_lml_cache_tables(self):
        pg = AsyncMock(spec=PgSource)
        pg.execute = AsyncMock(return_value="CREATE")

        await set_up_discogs_rate_bucket_schema(
            pg, bucket_key="discogs", capacity=50, refill_per_sec=50 / 60
        )

        executed = [call.args[0] for call in pg.execute.await_args_list]
        assert not any("streaming_url_cache" in sql for sql in executed)
        assert not any("api_keys" in sql for sql in executed)
