"""Unit tests for ``fetch_positive_class_synthetic_typos``.

The DB-backed positive-class fetchers (variations, entity.identity,
close-pairs) don't have unit tests in this repo — they're tested
end-to-end via the calibration script's integration runs. The synthetic
fetcher is different: its is_positive logic is non-trivial (the typo's
canonical_id has to equal the top trigram match's id) and worth pinning
without a real Postgres in the loop.

The pool is mocked. We assert (1) two queries are issued: artist sample +
bulk LATERAL, (2) the bulk query receives typos generated by generate_typos
keyed on the sampled names, and (3) the resulting CandidateScore list
correctly labels is_positive based on top_id == canonical_id.
"""

from __future__ import annotations

from unittest.mock import AsyncMock

import pytest

from scripts.resolver_calibration.__main__ import (
    CandidateScore,
    fetch_positive_class_synthetic_typos,
)
from scripts.resolver_calibration.synthetic_typos import generate_typos


@pytest.mark.asyncio
async def test_empty_sample_returns_empty_list():
    """No artists sampled → no bulk query issued, empty result."""
    pool = AsyncMock()
    pool.fetch = AsyncMock(side_effect=[[]])

    result = await fetch_positive_class_synthetic_typos(pool, n_artists=10)

    assert result == []
    # Only the sample query should fire; no bulk query when there are no typos.
    assert pool.fetch.await_count == 1


@pytest.mark.asyncio
async def test_short_names_produce_no_typos_skip_bulk_query():
    """Artists whose names are too short to corrupt (<4 chars) yield empty
    typo lists. If every sampled artist is too short, no bulk query fires."""
    pool = AsyncMock()
    pool.fetch = AsyncMock(
        side_effect=[
            [{"id": 1, "name": "abc"}, {"id": 2, "name": "ab"}],
            [],  # would-be bulk query — should NOT be reached
        ]
    )

    result = await fetch_positive_class_synthetic_typos(pool, n_artists=2)

    assert result == []
    assert pool.fetch.await_count == 1


@pytest.mark.asyncio
async def test_is_positive_when_top_id_matches_canonical():
    """The core labeling contract: a row is a true positive when the
    LATERAL join's top match has the same id as the typo's canonical
    artist."""
    pool = AsyncMock()
    # Sample one artist, then bulk-query result: top match is the same id.
    pool.fetch = AsyncMock(
        side_effect=[
            [{"id": 42, "name": "Stereolab"}],
            [
                {
                    "typo": "Setreolab",
                    "canonical_id": 42,
                    "canonical_name": "Stereolab",
                    "top_id": 42,  # matches canonical_id → is_positive
                    "top_name": "Stereolab",
                    "top_score": 0.85,
                }
            ],
        ]
    )

    result = await fetch_positive_class_synthetic_typos(pool, n_artists=1, typos_per_artist=1)

    assert len(result) == 1
    assert result[0].is_positive is True
    assert result[0].score == 0.85
    assert result[0].query_name == "Setreolab"


@pytest.mark.asyncio
async def test_is_negative_when_top_id_differs():
    """The complementary case: top match is a different artist (e.g.
    'Setreolab' resolves to some unrelated artist with id 999). Recorded
    as is_positive=False so the threshold sweep counts it correctly."""
    pool = AsyncMock()
    pool.fetch = AsyncMock(
        side_effect=[
            [{"id": 42, "name": "Stereolab"}],
            [
                {
                    "typo": "Setreolab",
                    "canonical_id": 42,
                    "canonical_name": "Stereolab",
                    "top_id": 999,  # different artist → is_positive=False
                    "top_name": "Other Artist",
                    "top_score": 0.55,
                }
            ],
        ]
    )

    result = await fetch_positive_class_synthetic_typos(pool, n_artists=1, typos_per_artist=1)

    assert len(result) == 1
    assert result[0].is_positive is False
    assert result[0].top_id == 999


@pytest.mark.asyncio
async def test_handles_null_top_match():
    """When pg_trgm finds no candidate within the similarity floor, the
    LATERAL join returns NULLs for top_id / top_name / top_score. The
    fetcher must coerce these into a CandidateScore with score=0.0 and
    is_positive=False rather than crashing."""
    pool = AsyncMock()
    pool.fetch = AsyncMock(
        side_effect=[
            [{"id": 42, "name": "Stereolab"}],
            [
                {
                    "typo": "Setreolab",
                    "canonical_id": 42,
                    "canonical_name": "Stereolab",
                    "top_id": None,
                    "top_name": None,
                    "top_score": None,
                }
            ],
        ]
    )

    result = await fetch_positive_class_synthetic_typos(pool, n_artists=1, typos_per_artist=1)

    assert len(result) == 1
    assert result[0].score == 0.0
    assert result[0].is_positive is False
    assert result[0].top_id is None


@pytest.mark.asyncio
async def test_typos_passed_to_bulk_query_match_generator_output():
    """The bulk query's first parameter is the list of generated typos.
    Verify it matches what ``generate_typos`` returns for the sampled
    name — pins the integration between the generator and the SQL probe."""
    pool = AsyncMock()
    pool.fetch = AsyncMock(
        side_effect=[
            [{"id": 42, "name": "Stereolab"}],
            [],
        ]
    )

    await fetch_positive_class_synthetic_typos(pool, n_artists=1, typos_per_artist=3)

    # Second fetch call is the bulk query; args are (sql, typos, ids, names).
    bulk_call = pool.fetch.await_args_list[1]
    typos_passed = bulk_call.args[1]
    expected_typos = generate_typos("Stereolab", seed=hash("Stereolab"), max_typos=3)
    assert typos_passed == expected_typos
    # Every typo's canonical id should be 42 (the only sampled artist's id).
    canonical_ids_passed = bulk_call.args[2]
    assert canonical_ids_passed == [42] * len(expected_typos)


@pytest.mark.asyncio
async def test_returns_candidate_score_instances():
    """The harness expects ``list[CandidateScore]`` so the threshold sweep
    can mix this class's output with the variation / identity / close-pair
    classes."""
    pool = AsyncMock()
    pool.fetch = AsyncMock(
        side_effect=[
            [{"id": 42, "name": "Stereolab"}],
            [
                {
                    "typo": "Setreolab",
                    "canonical_id": 42,
                    "canonical_name": "Stereolab",
                    "top_id": 42,
                    "top_name": "Stereolab",
                    "top_score": 0.85,
                }
            ],
        ]
    )

    result = await fetch_positive_class_synthetic_typos(pool, n_artists=1, typos_per_artist=1)

    assert all(isinstance(r, CandidateScore) for r in result)
